### ISSUE TITLE
No account with IBAN DE843701900010XXXXXXXX - suddenly a single bunq account does not sync anymore

### ISSUE THREAD

**Issue by Taimonania** [wesselt/bunq2ynab#57] opened 2024-02-26 17:32 UTC
A few days ago the sync of one of my bunq accounts suddenly started failing. It works for all other accounts, and I have not changed this account on bunq or YNAB.

The only thing I could find in the logs is this. Xs for anonymity. It is the correct IBAN of my bunq account:

```
2024-02-20 08:58:17,626 \| INFO \| config.py:80 \| read_ssm_config \| Reading config from SSM 
2024-02-20 08:58:19,096 \| INFO \| credentials.py:1114 \| load \| Found credentials in environment variables.
2024-02-20 08:58:19,396 \| INFO \| lambda_function.py:41 \| get_iban_from_event \| Found IBAN DE843701900010XXXXXXXX in request body
2024-02-20 08:58:19,396 \| INFO \| sync.py:60 \| populate \| Retrieving bunq accounts...
2024-02-20 08:58:19,396 \| INFO \| state.py:32 \| load \| Fetching SSM state bunq2ynab-state
2024-02-20 08:58:19,969 \| INFO \| sync.py:62 \| populate \| Retrieving ynab accounts...
2024-02-20 08:58:20,486 \| WARNING \| sync.py:203 \| synchronize_iban \| No account with IBAN DE843701900010DE843701900010XXXXXXXX
2024-02-20 08:58:20,486 \| INFO \| lambda_function.py:13 \| add_callbacks \| SSM callback = "https://xig3nh4xyg.execute-api.eu-north-1.amazonaws.com/bunq2ynab-lambda"
2024-02-20 08:58:20,486 \| INFO \| lambda_function.py:16 \| add_callbacks \| Adding callbacks...
END RequestId: 25fd072f-97ef-4f58-a754-c05c18bf1c32
```

This is the log just two days before doing the same sync and succeeding:

```
START RequestId: c7bc55de-46c3-4ffb-863c-dd8931601c40 Version: $LATEST
2024-02-18 12:08:27,642 \| INFO \| config.py:80 \| read_ssm_config \| Reading config from SSM
2024-02-18 12:08:27,708 \| INFO \| lambda_function.py:41 \| get_iban_from_event \| Found IBAN DE843701900010XXXXXXXX in request body
2024-02-18 12:08:27,709 \| INFO \| sync.py:60 \| populate \| Retrieving bunq accounts...
2024-02-18 12:08:28,227 \| INFO \| sync.py:62 \| populate \| Retrieving ynab accounts...
2024-02-18 12:08:28,735 \| INFO \| sync.py:158 \| synchronize_account \| Synching "Timo XXXX" - "Lebenshaltung" to "Timos Budget" - "Lebenshaltung"...
2024-02-18 12:08:28,735 \| INFO \| sync.py:167 \| synchronize_account \| Reading ynab transactions from 2024-01-14...
2024-02-18 12:08:29,245 \| INFO \| sync.py:170 \| synchronize_account \| Retrieved 60 ynab transactions...
2024-02-18 12:08:29,245 \| INFO \| sync.py:176 \| synchronize_account \| Reading bunq payments from 2024-02-18...
2024-02-18 12:08:30,083 \| INFO \| bunq_api.py:151 \| get_payments \| Retrieved back to 2023-11-23...
2024-02-18 12:08:30,083 \| INFO \| sync.py:179 \| synchronize_account \| Retrieved 1 bunq payments...
2024-02-18 12:08:30,084 \| INFO \| sync.py:191 \| synchronize_account \| "Timo XXXX" - "Lebenshaltung" to "Timos Budget" - "Lebenshaltung": Created 0 and patched 0 transactions.
2024-02-18 12:08:30,084 \| INFO \| lambda_function.py:13 \| add_callbacks \| SSM callback = "https://xig3nh4xyg.execute-api.eu-north-1.amazonaws.com/bunq2ynab-lambda"
2024-02-18 12:08:30,084 \| INFO \| lambda_function.py:16 \| add_callbacks \| Adding callbacks...
END RequestId: c7bc55de-46c3-4ffb-863c-dd8931601c40
```

Does anyone have any idea what the problem is or how to fix it? Please let me know if you need any other logs or anything, I will gladly provide more necessary info that I'm not aware of yet.

**Comment by wesselt** [comment] 2024-02-26 18:42
There's been a few tickets about missing accounts.  The cause looks like change pagination, so that not all accounts are considered when synching. A quick fix was committed: https://github.com/wesselt/bunq2ynab/commit/2435ae11e48b29a69e6d0db35df9531220ae911b

How does the latest version on the master branch work for you?

**Comment by Taimonania** [comment] 2024-02-26 19:11
Thank you for the quick reply and help!

I am running this on AWS Lambda with the template described in the README. Is there an easy way for me to sync the code?

EDIT: never mind, I found your answer from a few days ago and will go with that. For anyone coming here later: https://github.com/wesselt/bunq2ynab/issues/53#issuecomment-1959009857

**Closed as completed** 2024-02-27 21:09 UTC
