### ISSUE TITLE
Missing payments / Sorted payments

### ISSUE THREAD

**Issue by MagicLegend** [wesselt/bunq2ynab#20] opened 2020-07-28 11:36 UTC
Hi,

I have set up the AWS lambda 'fork' for these scripts (https://github.com/rvdh/aws_lambda_bunq2ynab), however, I am running into issues. As the title says, I am missing payments. On every account I miss the oldest few payments, anywhere from 1 to 15 payments. This makes me wonder how many other payments are missing. Re-running the lambda just returns that it added duplicate payments for all the accounts, and no new ones.

Also, when a payment gets auto-sorted; it shows up on the wrong account (it shows up as a single payment on the original account; but never actually gets connected to the other accounts). Is this something that I have to link in YNAB?

Thanks for the work!

**Comment by MagicLegend** [comment] 2020-07-28 11:39
I just noticed https://github.com/wesselt/bunq2ynab/tree/python35 on this repo, which would make the lambda actually run outdated code. Is this something that got fixed in between perhaps?

**Comment by wesselt** [comment] 2020-07-28 12:11
Hi MagicLegend,

A syncs retrieves the last 100 payments. It's meant to process recent changes every time there is a transaction. I'll check if I can improve something here.

To get all history in YNAB, you can retrieve a CSV from Bunq from Account > Lightning > Export Statement and import the CSV into YNAB.

The python35 branch contains improvements I'm still working on. My goal is to auto approve the ZeroFX corrections Bunq sends for every transaction in foreign currency.

The auto-sort sounds interesting. I haven't used that feature. How can I reproduce that?

**Comment by MagicLegend** [comment] 2020-07-28 12:44
Hi Wessel!

Thanks for your response!

- Yeah, with the help of @rdvh I found out that it only tried to sync the last 100 payments. This of course works for syncing daily; but for the initial sync this is not enough. Maybe there should be a special 'first sync' mode that will try to take the first 10k payments or something?
- Maybe I should use that for now. I tried increasing the amount of payments in the code, but that just threw an error:
```
{
  "errorMessage": "You cannot ask for more than \"200\" elements from an API call (asked \"10000\").",
  "errorType": "Exception",
  "stackTrace": [
    "  File \"/var/task/auto_sync.py\", line 115, in sync\n    sync_bunq_to_ynab(bunq_user_id, bunq_account_id, ynab_budget_id, ynab_account_id)\n",
    "  File \"/var/task/auto_sync.py\", line 82, in sync_bunq_to_ynab\n    transactions = bunq_api.get_transactions(bunq_user_id, bunq_account_id)\n",
    "  File \"/var/task/bunq_api.py\", line 48, in get_transactions\n    payments = bunq.get(method)\n",
    "  File \"/var/task/bunq.py\", line 251, in get\n    return call('GET', method)\n",
    "  File \"/var/task/bunq.py\", line 235, in call\n    raise Exception(result[\"Error\"][0][\"error_description\"])\n"
  ]
}
```
This would suggest to me that I would have to edit some more code to make multiple requests of 200 each. Perhaps this is something that should be included as a `first sync` mode?

- Alright, we guessed that already. I'll just keep an eye on your work when you merge it to master :)

- Yeah, simple. Just [enable the feature](https://www.bunq.com/benefits/sorter) and make it redirect the money to a different account. I don't actually 'split' the payment, but I just forward it all to another account. Note that this payment does not include the original comment anymore. When you use requests to internally move money around, the payment will include the original comment.

**Comment by wesselt** [comment] 2020-07-28 12:47
Quick idea: have you tried omitting the count parameter altogether?

I've [asked on Together](https://together.bunq.com/d/35087-api-parameters-for-retrieving-payments) for more information about getting transactions.

**Comment by MagicLegend** [comment] 2020-07-28 13:03
> Quick idea: have you tried omitting the count parameter altogether?

Hah, as you sent that I was also going through the Bunq docs to find what I could do; and tried this too. However, it seems to only return 10 items or so, given that the logging returns that it found 5-9 duplicate payments and 0 new ones (which is still odd; since _all_ payments should be duplicate by now?)

**Comment by MagicLegend** [comment] 2020-07-28 13:38
I've been sniffing around the official SDK's to see if I could find more info about the endpoint; and it seems like `count` is the only parameter... https://github.com/bunq/tinker_python/blob/2182b8be276fda921657ad22cfe0b8b48a585ccf/tinker/libs/bunq_lib.py#L105-L115

**Comment by MagicLegend** [comment] 2020-07-28 13:43
And then I realize that I should check the community-SDK because that one is gonna be better documented than the official one (Bunq really cares about it's users eh? :p); and yes: there are more parameters possible:

https://github.com/bunqCommunity/bunqJSClient/blob/6a874e00ebfa8365b76ef0678938e8dd28ef5536/src/Api/Payment.ts#L43-L86

**Comment by MagicLegend** [comment] 2020-07-28 14:25
So: in conclusion, there should be a loop that just keeps retrieving payments until `newer_url` in the response is set to `null`, as per the [docs](https://beta.doc.bunq.com/basics/pagination). That way it would be possible to retrieve every payment for that account; thus filling Ynab with every payment that was ever made.

Are you aware of any API rate limits on either API's that could prohibit the mass-import like this?

**Comment by wesselt** [comment] 2020-07-28 15:06
Bastiaan answered on Together that the documentation is here: https://doc.bunq.com/#/pagination

I think I'll try this: first retrieve the last transaction from YNAB, then retrieve transactions from Bunq until I get to the date of the last YNAB transaction. I'll post an update tomorrow, perhaps you could help test it.

**Comment by MagicLegend** [comment] 2020-07-29 09:06
Sounds good, I hope you can implement it soon (so I can actually start using YNAB; all the balances are off now because of the missing transactions)! And I will of course gladly test the functionality.

As for the auto-sort issue, this is something that you could probably reproduce yourself if you can make a payment from another bank to yourself (this seems to be a requirement to be able to split a payment).

**Comment by wesselt** [comment] 2020-07-29 19:00
The current version of the [python35 branch](https://github.com/wesselt/bunq2ynab/tree/python35) should upload all transactions if you start with a clean account, or an account with only a "Starting Balance" transaction.

Once that part works I'll have a look at the auto sorting.

**Comment by MagicLegend** [comment] 2020-07-30 08:18
Glad to hear. However, I am now in the unique position where I have imported parts of my transactions, and older ones are still missing. What would be the best course of action here? Could I simply take the CSV export out of Bunq to resolve this, or do I need to modify the script to do it for me (to resolve any matching issues)?

**Comment by wesselt** [comment] 2020-07-30 08:58
I've added an --all flag to bunq2ynab.py, does that work for you?

**Comment by MagicLegend** [comment] 2020-07-30 14:04
I think that would work! I'll give it a try tomorrow :) Thanks!

**Comment by MagicLegend** [comment] 2020-07-31 12:18
> I've added an --all flag to bunq2ynab.py, does that work for you?

I have just tried this out, but it doesn't appear to be working. Logs:
```
$ python3 bunq2ynab.py --all "<My name>" "<Bunq account name>" "<My Budget>" "<Ynab account>"
Getting ynab identifiers...
Getting bunq identifiers...
Reading ynab transactions from 2000-01-01...
Retrieved 102 ynab transactions...
Reading bunq payments from 2020-07-29...
Retrieved back to 2019-01-29...
Retrieved 3 bunq payments...
Merging ZeroFX duplicates...
Created 0 and patched 0 transactions.
```

The `2019-01-29` date is **correct**, this is the first transaction of the account. However, in YNAB the earliest transaction is still `2019-11-19`; aka 10 months of data missing... Also your logging is maybe a bit awkward, since I assume this means it retrieved `3 * 200` payments; not 3?

If you want verbose logging I could look into how I can anonymize that. Thank you for thinking with me! :)

**Comment by wesselt** [comment] 2020-07-31 14:30
Aha, thanks for posting the log, that makes it easy. The date from the last YNAB entry overwrote the start date. It retrieves at least 200 entries but uses only the ones after the start date, so that was just 3 entries. I've fixed that in the latest commit.

How does it work with the latest version?

**Comment by MagicLegend** [comment] 2020-07-31 15:06
I can confirm that the latest version fixed it; and it's all working now! Thank you so so much 😊

**Comment by wesselt** [comment] 2020-07-31 15:47
Good to hear!  Let me know if you encounter any other issues.

**Comment by MagicLegend** [comment] 2020-07-31 18:37
I'm afraid I did: compared to what https://github.com/rvdh/aws_lambda_bunq2ynab did; it seems like this import did not recognize transfers between my own accounts correctly. There are payments that have the correct description, but are not recognized as '`transferred from <account>'`; making them a lot (and I mean a _lot_) of manual work... Is this something that can be fixed post-importing, or is this just screwed and should I try to re-import from scratch (not sure how to delete everything, but I'm sure I'll figure it out :D)?

![image](https://user-images.githubusercontent.com/3169104/89066479-352d8a00-d376-11ea-9681-b061e8fc986d.png)
_The first is a payment between my own accounts as imported, the second is how I would have expected them to be imported_

**Comment by wesselt** [comment] 2020-08-01 08:49
As far as I can see the python35 version and rvdh's version upload the same data. What might happen is that once you mark one transaction as a transfer, YNAB automatically recognizes future transactions as transfers.

You can delete transactions in YNAB by selecting them all (with the select-all checkbox), then Edit > Delete, then right click the account and delete the account. If you don't delete the account, it will remember the transactions as having been deleted by the user, and won't accept them from from bunq2ynab.

I've asked on the [YNAB forum](url) how they recognize transfers: https://support.youneedabudget.com/t/p8h8xsd

**Comment by MagicLegend** [comment] 2020-08-01 18:27
> You can delete transactions in YNAB by selecting them all (with the select-all checkbox), then Edit > Delete, then right click the account and delete the account. If you don't delete the account, it will remember the transactions as having been deleted by the user, and won't accept them from from bunq2ynab.

Even after creating a new Budget, it was still broken... :(

> I've asked on the YNAB forum how they recognize transfers: https://support.youneedabudget.com/t/p8h8xsd

I have had contact with YNAB as well, and they told me that the recognition was purely based on the `Payee` field. So, I suspect that as a quick fix, every payment (or `transfer` in the API's terms) to each unique subaccount should just have it's own payee. `CJ Johnson Savings` and `CJ Johnson Groceries` (or `CJ Johnson NL85BUNQ123456789`) for example, instead of just `CJ Johnson` for every transfer. If I'm not mistaken it should be the _target_ name/IBAN that should be included; but I might be making a mistake in how YNAB picks up the naming scheme. I think this idea could solve the issue for now.

However, could it be that this should be done on an import level, and this tool should provide the structure completely? Isn't that what the [`SubTransaction`](https://api.youneedabudget.com/v1) model is for? If you set the `subtransactions.payee_id` (`SaveTransaction` model) upon creating the transaction, will it create the transaction correctly as a `transfer transaction`?

**Comment by wesselt** [comment] 2020-08-02 09:42
A sub transaction is probably a split payment. For example, you can split a bunq payment for 50 euros into two YNAB transactions: 30 euro for groceries and 20 euro for gifts. This wouldn't help with transfers.

Nicole from YNAB support asks if you see anything in the tooltip of the Payee?  Can you still check that?

The latest commit adds the IBAN to the payee description. In YNAB, you can open the menu (top left), then Manage Payees. Search for a  payee called "Transfer: accountname", and you can add a rule that automatically categorises something as a transfer.

**Comment by MagicLegend** [comment] 2020-08-02 13:25
> A sub transaction is probably a split payment.

Given the Models specified in the API docs I don't think that's true:

![image](https://user-images.githubusercontent.com/3169104/89122637-6f5f6e80-d4d1-11ea-990c-61534c0fef36.png)
(`TransactionDetail.subtransactions`)

I think that if you can fill these in, it would become a Transfer. Maybe you can verify that by GET-ting a Transfer payment from YNAB and see how the response looks like?

> Nicole from YNAB support asks if you see anything in the tooltip of the Payee? Can you still check that?

What tooltip are you referring to here? The `Payee` field is filled with my name, however; as I have multiple accounts under the same name, YNAB gets confused about it.

> The latest commit adds the IBAN to the payee description.

I have deleted everything and reimported with the new code, and **this indeed fixes the issue for me**. Amazing! Thank you so so much! However, I think there should be a more permanent solution from YNAB's side for this. I wonder how I am the only one running into this issue? Is it that unique to have multiple accounts under the same name á la bunq?

**Comment by wesselt** [comment] 2020-08-02 14:01
Cool, I hadn't noticed the Model section below, only saw this:

![image](https://user-images.githubusercontent.com/7126336/89124645-e9472600-d4d8-11ea-9988-8e61032cbd57.png)

Still it doesn't look like you can save the transfer_transaction_id property. It's not in the SaveTransaction model.

> I wonder how I am the only one running into this issue? Is it that unique to have multiple accounts under the same name á la bunq?

Since YNAB doesn't care about accounts, one account in Bunq suits all my needs. It's also unusual to really care about past transactions in YNAB. I do a [fresh start](https://www.youneedabudget.com/the-logic-art-of-a-ynab-fresh-start/) every now and then, and at that point I forget about the past.

I'm still working to sync all accounts and store the configuration in a single file or the environment.

**Comment by wesselt** [comment] 2020-08-02 20:37
I'll close this issue, let me know if you encounter anything else!

**Closed as completed by wesselt** 2020-08-02 20:37 UTC

**Comment by MagicLegend** [comment] 2020-08-06 17:40
> Since YNAB doesn't care about accounts, one account in Bunq suits all my needs. It's also unusual to really care about past transactions in YNAB. I do a fresh start every now and then, and at that point I forget about the past.

My hopes was to 'train' the AI with all my previous transactions, since a lot can be learnt from them. However; it seems that beyond that I already have knowledge about payees, there is no real benefit...

I bluntly ripped the IBAN code from https://github.com/wesselt/bunq2ynab/commit/854abf to make the mentioned Lambda function compatible with this import code (because I used this to import the full backlog, thus teaching YNAB the payees with IBAN attached. However, I use the Lambda to import transactions as they happen) in https://github.com/MagicLegend/aws_lambda_bunq2ynab/commit/805ca9. I hope you won't mind too much :)

Once you consider the https://github.com/wesselt/bunq2ynab/tree/python35 branch 'stable', I would love to have a ping. Then I can try to work with @rvdh to also push these updates to the Lambda.

**Comment by wesselt** [comment] 2020-08-07 10:36
Based on what [Fanes said on YNAB support](https://support.youneedabudget.com/t/p8h8xsd) I've added support for transfers. If both accounts are included in the sync, it will look up the IBAN and assign the transfer_payee_id of the other account. Detecting that transfer in the other account was kind of complicated but it looks like it works now.

All the new code is in the config branch. Got some explanation about Lambda from a video call with @rvdh. Perhaps you can join in on https://github.com/wesselt/bunq2ynab/issues/14 ?
